window.ALL_COUNTRIES = [
  {
    "cca2": "AF",
    "official": "Islamic Republic of Afghanistan",
    "region": "Asia",
    "area": 652230,
    "drive": "Right",
    "languages": "Pashto, Dari",
    "timezones": "UTC+04:30",
    "capital": "Kabul",
    "subregion": "Southern Asia",
    "population": 41128771,
    "name": "Afghanistan",
    "calling": "+93",
    "cca3": "AFG",
    "currency": "AFN (؋) - Afghan Afghani",
    "flag": "https://flagcdn.com/w160/af.png"
  },
  {
    "cca2": "AL",
    "official": "Republic of Albania",
    "region": "Europe",
    "area": 28748,
    "drive": "Right",
    "languages": "Albanian",
    "timezones": "UTC+01:00",
    "capital": "Tirana",
    "subregion": "Southern Europe",
    "population": 2775634,
    "name": "Albania",
    "calling": "+355",
    "cca3": "ALB",
    "currency": "ALL (L) - Albanian Lek",
    "flag": "https://flagcdn.com/w160/al.png"
  },
  {
    "cca2": "DZ",
    "official": "People's Democratic Republic of Algeria",
    "region": "Africa",
    "area": 2381741,
    "drive": "Right",
    "languages": "Arabic, Berber",
    "timezones": "UTC+01:00",
    "capital": "Algiers",
    "subregion": "Northern Africa",
    "population": 44903225,
    "name": "Algeria",
    "calling": "+213",
    "cca3": "DZA",
    "currency": "DZD (د.ج) - Algerian Dinar",
    "flag": "https://flagcdn.com/w160/dz.png"
  },
  {
    "cca2": "AD",
    "official": "Principality of Andorra",
    "region": "Europe",
    "area": 468,
    "drive": "Right",
    "languages": "Catalan",
    "timezones": "UTC+01:00",
    "capital": "Andorra la Vella",
    "subregion": "Southern Europe",
    "population": 79824,
    "name": "Andorra",
    "calling": "+376",
    "cca3": "AND",
    "currency": "EUR (€) - Euro",
    "flag": "https://flagcdn.com/w160/ad.png"
  },
  {
    "cca2": "AO",
    "official": "Republic of Angola",
    "region": "Africa",
    "area": 1246700,
    "drive": "Right",
    "languages": "Portuguese",
    "timezones": "UTC+01:00",
    "capital": "Luanda",
    "subregion": "Middle Africa",
    "population": 35588987,
    "name": "Angola",
    "calling": "+244",
    "cca3": "AGO",
    "currency": "AOA (Kz) - Angolan Kwanza",
    "flag": "https://flagcdn.com/w160/ao.png"
  },
  {
    "cca2": "AG",
    "official": "Antigua and Barbuda",
    "region": "Americas",
    "area": 442,
    "drive": "Left",
    "languages": "English",
    "timezones": "UTC-04:00",
    "capital": "St. John's",
    "subregion": "Caribbean",
    "population": 93763,
    "name": "Antigua and Barbuda",
    "calling": "+1-268",
    "cca3": "ATG",
    "currency": "XCD ($) - East Caribbean Dollar",
    "flag": "https://flagcdn.com/w160/ag.png"
  },
  {
    "cca2": "AR",
    "official": "Argentine Republic",
    "region": "Americas",
    "area": 2780400,
    "drive": "Right",
    "languages": "Spanish",
    "timezones": "UTC-03:00",
    "capital": "Buenos Aires",
    "subregion": "South America",
    "population": 46234830,
    "name": "Argentina",
    "calling": "+54",
    "cca3": "ARG",
    "currency": "ARS ($) - Argentine Peso",
    "flag": "https://flagcdn.com/w160/ar.png"
  },
  {
    "cca2": "AM",
    "official": "Republic of Armenia",
    "region": "Asia",
    "area": 29743,
    "drive": "Right",
    "languages": "Armenian",
    "timezones": "UTC+04:00",
    "capital": "Yerevan",
    "subregion": "Western Asia",
    "population": 2780469,
    "name": "Armenia",
    "calling": "+374",
    "cca3": "ARM",
    "currency": "AMD (֏) - Armenian Dram",
    "flag": "https://flagcdn.com/w160/am.png"
  },
  {
    "cca2": "AU",
    "official": "Commonwealth of Australia",
    "region": "Oceania",
    "area": 7692024,
    "drive": "Left",
    "languages": "English",
    "timezones": "UTC+08:00 to UTC+10:30",
    "capital": "Canberra",
    "subregion": "Australia and New Zealand",
    "population": 26177413,
    "name": "Australia",
    "calling": "+61",
    "cca3": "AUS",
    "currency": "AUD ($) - Australian Dollar",
    "flag": "https://flagcdn.com/w160/au.png"
  },
  {
    "cca2": "AT",
    "official": "Republic of Austria",
    "region": "Europe",
    "area": 83871,
    "drive": "Right",
    "languages": "German",
    "timezones": "UTC+01:00",
    "capital": "Vienna",
    "subregion": "Western Europe",
    "population": 9042528,
    "name": "Austria",
    "calling": "+43",
    "cca3": "AUT",
    "currency": "EUR (€) - Euro",
    "flag": "https://flagcdn.com/w160/at.png"
  },
  {
    "cca2": "AZ",
    "official": "Republic of Azerbaijan",
    "region": "Asia",
    "area": 86600,
    "drive": "Right",
    "languages": "Azerbaijani",
    "timezones": "UTC+04:00",
    "capital": "Baku",
    "subregion": "Western Asia",
    "population": 10141756,
    "name": "Azerbaijan",
    "calling": "+994",
    "cca3": "AZE",
    "currency": "AZN (₼) - Azerbaijani Manat",
    "flag": "https://flagcdn.com/w160/az.png"
  },
  {
    "cca2": "BS",
    "official": "Commonwealth of the Bahamas",
    "region": "Americas",
    "area": 13943,
    "drive": "Left",
    "languages": "English",
    "timezones": "UTC-05:00",
    "capital": "Nassau",
    "subregion": "Caribbean",
    "population": 409984,
    "name": "Bahamas",
    "calling": "+1-242",
    "cca3": "BHS",
    "currency": "BSD ($) - Bahamian Dollar",
    "flag": "https://flagcdn.com/w160/bs.png"
  },
  {
    "cca2": "BH",
    "official": "Kingdom of Bahrain",
    "region": "Asia",
    "area": 765,
    "drive": "Right",
    "languages": "Arabic",
    "timezones": "UTC+03:00",
    "capital": "Manama",
    "subregion": "Western Asia",
    "population": 1472233,
    "name": "Bahrain",
    "calling": "+973",
    "cca3": "BHR",
    "currency": "BHD (.د.ب) - Bahraini Dinar",
    "flag": "https://flagcdn.com/w160/bh.png"
  },
  {
    "cca2": "BD",
    "official": "People's Republic of Bangladesh",
    "region": "Asia",
    "area": 147570,
    "drive": "Left",
    "languages": "Bengali",
    "timezones": "UTC+06:00",
    "capital": "Dhaka",
    "subregion": "Southern Asia",
    "population": 171186372,
    "name": "Bangladesh",
    "calling": "+880",
    "cca3": "BGD",
    "currency": "BDT (৳) - Bangladeshi Taka",
    "flag": "https://flagcdn.com/w160/bd.png"
  },
  {
    "cca2": "BB",
    "official": "Barbados",
    "region": "Americas",
    "area": 430,
    "drive": "Left",
    "languages": "English",
    "timezones": "UTC-04:00",
    "capital": "Bridgetown",
    "subregion": "Caribbean",
    "population": 281635,
    "name": "Barbados",
    "calling": "+1-246",
    "cca3": "BRB",
    "currency": "BBD ($) - Barbadian Dollar",
    "flag": "https://flagcdn.com/w160/bb.png"
  },
  {
    "cca2": "BY",
    "official": "Republic of Belarus",
    "region": "Europe",
    "area": 207600,
    "drive": "Right",
    "languages": "Belarusian, Russian",
    "timezones": "UTC+03:00",
    "capital": "Minsk",
    "subregion": "Eastern Europe",
    "population": 9208701,
    "name": "Belarus",
    "calling": "+375",
    "cca3": "BLR",
    "currency": "BYN (Br) - Belarusian Ruble",
    "flag": "https://flagcdn.com/w160/by.png"
  },
  {
    "cca2": "BE",
    "official": "Kingdom of Belgium",
    "region": "Europe",
    "area": 30528,
    "drive": "Right",
    "languages": "Dutch, French, German",
    "timezones": "UTC+01:00",
    "capital": "Brussels",
    "subregion": "Western Europe",
    "population": 11685814,
    "name": "Belgium",
    "calling": "+32",
    "cca3": "BEL",
    "currency": "EUR (€) - Euro",
    "flag": "https://flagcdn.com/w160/be.png"
  },
  {
    "cca2": "BZ",
    "official": "Belize",
    "region": "Americas",
    "area": 22966,
    "drive": "Right",
    "languages": "English, Spanish",
    "timezones": "UTC-06:00",
    "capital": "Belmopan",
    "subregion": "Central America",
    "population": 405272,
    "name": "Belize",
    "calling": "+501",
    "cca3": "BLZ",
    "currency": "BZD ($) - Belize Dollar",
    "flag": "https://flagcdn.com/w160/bz.png"
  },
  {
    "cca2": "BJ",
    "official": "Republic of Benin",
    "region": "Africa",
    "area": 112622,
    "drive": "Right",
    "languages": "French",
    "timezones": "UTC+01:00",
    "capital": "Porto-Novo",
    "subregion": "Western Africa",
    "population": 13352864,
    "name": "Benin",
    "calling": "+229",
    "cca3": "BEN",
    "currency": "XOF (Fr) - West African CFA Franc",
    "flag": "https://flagcdn.com/w160/bj.png"
  },
  {
    "cca2": "BT",
    "official": "Kingdom of Bhutan",
    "region": "Asia",
    "area": 38394,
    "drive": "Left",
    "languages": "Dzongkha",
    "timezones": "UTC+06:00",
    "capital": "Thimphu",
    "subregion": "Southern Asia",
    "population": 782455,
    "name": "Bhutan",
    "calling": "+975",
    "cca3": "BTN",
    "currency": "BTN (Nu.) - Bhutanese Ngultrum",
    "flag": "https://flagcdn.com/w160/bt.png"
  },
  {
    "cca2": "BO",
    "official": "Plurinational State of Bolivia",
    "region": "Americas",
    "area": 1098581,
    "drive": "Right",
    "languages": "Spanish, Quechua, Aymara",
    "timezones": "UTC-04:00",
    "capital": "Sucre",
    "subregion": "South America",
    "population": 12224110,
    "name": "Bolivia",
    "calling": "+591",
    "cca3": "BOL",
    "currency": "BOB (Bs.) - Bolivian Boliviano",
    "flag": "https://flagcdn.com/w160/bo.png"
  },
  {
    "cca2": "BA",
    "official": "Bosnia and Herzegovina",
    "region": "Europe",
    "area": 51209,
    "drive": "Right",
    "languages": "Bosnian, Croatian, Serbian",
    "timezones": "UTC+01:00",
    "capital": "Sarajevo",
    "subregion": "Southern Europe",
    "population": 3233526,
    "name": "Bosnia and Herzegovina",
    "calling": "+387",
    "cca3": "BIH",
    "currency": "BAM (KM) - Bosnia and Herzegovina Convertible Mark",
    "flag": "https://flagcdn.com/w160/ba.png"
  },
  {
    "cca2": "BW",
    "official": "Republic of Botswana",
    "region": "Africa",
    "area": 581730,
    "drive": "Left",
    "languages": "English, Tswana",
    "timezones": "UTC+02:00",
    "capital": "Gaborone",
    "subregion": "Southern Africa",
    "population": 2630296,
    "name": "Botswana",
    "calling": "+267",
    "cca3": "BWA",
    "currency": "BWP (P) - Botswanan Pula",
    "flag": "https://flagcdn.com/w160/bw.png"
  },
  {
    "cca2": "BR",
    "official": "Federative Republic of Brazil",
    "region": "Americas",
    "area": 8515767,
    "drive": "Right",
    "languages": "Portuguese",
    "timezones": "UTC-05:00 to UTC-02:00",
    "capital": "Brasília",
    "subregion": "South America",
    "population": 215313498,
    "name": "Brazil",
    "calling": "+55",
    "cca3": "BRA",
    "currency": "BRL (R$) - Brazilian Real",
    "flag": "https://flagcdn.com/w160/br.png"
  },
  {
    "cca2": "BN",
    "official": "Nation of Brunei, the Abode of Peace",
    "region": "Asia",
    "area": 5765,
    "drive": "Left",
    "languages": "Malay",
    "timezones": "UTC+08:00",
    "capital": "Bandar Seri Begawan",
    "subregion": "South-Eastern Asia",
    "population": 449002,
    "name": "Brunei",
    "calling": "+673",
    "cca3": "BRN",
    "currency": "BND ($) - Brunei Dollar",
    "flag": "https://flagcdn.com/w160/bn.png"
  },
  {
    "cca2": "BG",
    "official": "Republic of Bulgaria",
    "region": "Europe",
    "area": 110879,
    "drive": "Right",
    "languages": "Bulgarian",
    "timezones": "UTC+02:00",
    "capital": "Sofia",
    "subregion": "Eastern Europe",
    "population": 6447710,
    "name": "Bulgaria",
    "calling": "+359",
    "cca3": "BGR",
    "currency": "BGN (лв) - Bulgarian Lev",
    "flag": "https://flagcdn.com/w160/bg.png"
  },
  {
    "cca2": "BF",
    "official": "Burkina Faso",
    "region": "Africa",
    "area": 272967,
    "drive": "Right",
    "languages": "French",
    "timezones": "UTC+00:00",
    "capital": "Ouagadougou",
    "subregion": "Western Africa",
    "population": 22673762,
    "name": "Burkina Faso",
    "calling": "+226",
    "cca3": "BFA",
    "currency": "XOF (Fr) - West African CFA Franc",
    "flag": "https://flagcdn.com/w160/bf.png"
  },
  {
    "cca2": "BI",
    "official": "Republic of Burundi",
    "region": "Africa",
    "area": 27834,
    "drive": "Right",
    "languages": "Kirundi, French, English",
    "timezones": "UTC+02:00",
    "capital": "Gitega",
    "subregion": "Eastern Africa",
    "population": 12889576,
    "name": "Burundi",
    "calling": "+257",
    "cca3": "BDI",
    "currency": "BIF (Fr) - Burundian Franc",
    "flag": "https://flagcdn.com/w160/bi.png"
  },
  {
    "cca2": "CV",
    "official": "Republic of Cabo Verde",
    "region": "Africa",
    "area": 4033,
    "drive": "Right",
    "languages": "Portuguese",
    "timezones": "UTC-01:00",
    "capital": "Praia",
    "subregion": "Western Africa",
    "population": 593149,
    "name": "Cabo Verde",
    "calling": "+238",
    "cca3": "CPV",
    "currency": "CVE ($) - Cape Verdean Escudo",
    "flag": "https://flagcdn.com/w160/cv.png"
  },
  {
    "cca2": "KH",
    "official": "Kingdom of Cambodia",
    "region": "Asia",
    "area": 181035,
    "drive": "Right",
    "languages": "Khmer",
    "timezones": "UTC+07:00",
    "capital": "Phnom Penh",
    "subregion": "South-Eastern Asia",
    "population": 16767842,
    "name": "Cambodia",
    "calling": "+855",
    "cca3": "KHM",
    "currency": "KHR (៛) - Cambodian Riel",
    "flag": "https://flagcdn.com/w160/kh.png"
  },
  {
    "cca2": "CM",
    "official": "Republic of Cameroon",
    "region": "Africa",
    "area": 475442,
    "drive": "Right",
    "languages": "French, English",
    "timezones": "UTC+01:00",
    "capital": "Yaoundé",
    "subregion": "Middle Africa",
    "population": 27914536,
    "name": "Cameroon",
    "calling": "+237",
    "cca3": "CMR",
    "currency": "XAF (Fr) - Central African CFA Franc",
    "flag": "https://flagcdn.com/w160/cm.png"
  },
  {
    "cca2": "CA",
    "official": "Canada",
    "region": "Americas",
    "area": 9984670,
    "drive": "Right",
    "languages": "English, French",
    "timezones": "UTC-08:00 to UTC-03:30",
    "capital": "Ottawa",
    "subregion": "Northern America",
    "population": 38929902,
    "name": "Canada",
    "calling": "+1",
    "cca3": "CAN",
    "currency": "CAD ($) - Canadian Dollar",
    "flag": "https://flagcdn.com/w160/ca.png"
  },
  {
    "cca2": "CF",
    "official": "Central African Republic",
    "region": "Africa",
    "area": 622984,
    "drive": "Right",
    "languages": "French, Sango",
    "timezones": "UTC+01:00",
    "capital": "Bangui",
    "subregion": "Middle Africa",
    "population": 5579144,
    "name": "Central African Republic",
    "calling": "+236",
    "cca3": "CAF",
    "currency": "XAF (Fr) - Central African CFA Franc",
    "flag": "https://flagcdn.com/w160/cf.png"
  },
  {
    "cca2": "TD",
    "official": "Republic of Chad",
    "region": "Africa",
    "area": 1284000,
    "drive": "Right",
    "languages": "French, Arabic",
    "timezones": "UTC+01:00",
    "capital": "N'Djamena",
    "subregion": "Middle Africa",
    "population": 17723315,
    "name": "Chad",
    "calling": "+235",
    "cca3": "TCD",
    "currency": "XAF (Fr) - Central African CFA Franc",
    "flag": "https://flagcdn.com/w160/td.png"
  },
  {
    "cca2": "CL",
    "official": "Republic of Chile",
    "region": "Americas",
    "area": 756102,
    "drive": "Right",
    "languages": "Spanish",
    "timezones": "UTC-06:00 to UTC-04:00",
    "capital": "Santiago",
    "subregion": "South America",
    "population": 19603733,
    "name": "Chile",
    "calling": "+56",
    "cca3": "CHL",
    "currency": "CLP ($) - Chilean Peso",
    "flag": "https://flagcdn.com/w160/cl.png"
  },
  {
    "cca2": "CN",
    "official": "People's Republic of China",
    "region": "Asia",
    "area": 9596961,
    "drive": "Right",
    "languages": "Mandarin Chinese",
    "timezones": "UTC+08:00",
    "capital": "Beijing",
    "subregion": "Eastern Asia",
    "population": 1411750000,
    "name": "China",
    "calling": "+86",
    "cca3": "CHN",
    "currency": "CNY (¥) - Chinese Yuan",
    "flag": "https://flagcdn.com/w160/cn.png"
  },
  {
    "cca2": "CO",
    "official": "Republic of Colombia",
    "region": "Americas",
    "area": 1141748,
    "drive": "Right",
    "languages": "Spanish",
    "timezones": "UTC-05:00",
    "capital": "Bogotá",
    "subregion": "South America",
    "population": 51874024,
    "name": "Colombia",
    "calling": "+57",
    "cca3": "COL",
    "currency": "COP ($) - Colombian Peso",
    "flag": "https://flagcdn.com/w160/co.png"
  },
  {
    "cca2": "KM",
    "official": "Union of the Comoros",
    "region": "Africa",
    "area": 1862,
    "drive": "Right",
    "languages": "Comorian, Arabic, French",
    "timezones": "UTC+03:00",
    "capital": "Moroni",
    "subregion": "Eastern Africa",
    "population": 836774,
    "name": "Comoros",
    "calling": "+269",
    "cca3": "COM",
    "currency": "KMF (Fr) - Comorian Franc",
    "flag": "https://flagcdn.com/w160/km.png"
  },
  {
    "cca2": "CG",
    "official": "Republic of the Congo",
    "region": "Africa",
    "area": 342000,
    "drive": "Right",
    "languages": "French, Lingala, Kituba",
    "timezones": "UTC+01:00",
    "capital": "Brazzaville",
    "subregion": "Middle Africa",
    "population": 5970424,
    "name": "Congo (Republic)",
    "calling": "+242",
    "cca3": "COG",
    "currency": "XAF (Fr) - Central African CFA Franc",
    "flag": "https://flagcdn.com/w160/cg.png"
  },
  {
    "cca2": "CD",
    "official": "Democratic Republic of the Congo",
    "region": "Africa",
    "area": 2344858,
    "drive": "Right",
    "languages": "French, Lingala, Swahili",
    "timezones": "UTC+01:00 to UTC+02:00",
    "capital": "Kinshasa",
    "subregion": "Middle Africa",
    "population": 99010212,
    "name": "Congo (Democratic Republic)",
    "calling": "+243",
    "cca3": "COD",
    "currency": "CDF (Fr) - Congolese Franc",
    "flag": "https://flagcdn.com/w160/cd.png"
  },
  {
    "cca2": "CR",
    "official": "Republic of Costa Rica",
    "region": "Americas",
    "area": 51100,
    "drive": "Right",
    "languages": "Spanish",
    "timezones": "UTC-06:00",
    "capital": "San José",
    "subregion": "Central America",
    "population": 5180829,
    "name": "Costa Rica",
    "calling": "+506",
    "cca3": "CRI",
    "currency": "CRC (₡) - Costa Rican Colón",
    "flag": "https://flagcdn.com/w160/cr.png"
  },
  {
    "cca2": "HR",
    "official": "Republic of Croatia",
    "region": "Europe",
    "area": 56594,
    "drive": "Right",
    "languages": "Croatian",
    "timezones": "UTC+01:00",
    "capital": "Zagreb",
    "subregion": "Southern Europe",
    "population": 3855641,
    "name": "Croatia",
    "calling": "+385",
    "cca3": "HRV",
    "currency": "EUR (€) - Euro",
    "flag": "https://flagcdn.com/w160/hr.png"
  },
  {
    "cca2": "CU",
    "official": "Republic of Cuba",
    "region": "Americas",
    "area": 109884,
    "drive": "Right",
    "languages": "Spanish",
    "timezones": "UTC-05:00",
    "capital": "Havana",
    "subregion": "Caribbean",
    "population": 11212191,
    "name": "Cuba",
    "calling": "+53",
    "cca3": "CUB",
    "currency": "CUP ($) - Cuban Peso",
    "flag": "https://flagcdn.com/w160/cu.png"
  },
  {
    "cca2": "CY",
    "official": "Republic of Cyprus",
    "region": "Europe",
    "area": 9251,
    "drive": "Left",
    "languages": "Greek, Turkish",
    "timezones": "UTC+02:00",
    "capital": "Nicosia",
    "subregion": "Southern Europe",
    "population": 1251488,
    "name": "Cyprus",
    "calling": "+357",
    "cca3": "CYP",
    "currency": "EUR (€) - Euro",
    "flag": "https://flagcdn.com/w160/cy.png"
  },
  {
    "cca2": "CZ",
    "official": "Czech Republic",
    "region": "Europe",
    "area": 78866,
    "drive": "Right",
    "languages": "Czech",
    "timezones": "UTC+01:00",
    "capital": "Prague",
    "subregion": "Central Europe",
    "population": 10516707,
    "name": "Czech Republic",
    "calling": "+420",
    "cca3": "CZE",
    "currency": "CZK (Kč) - Czech Koruna",
    "flag": "https://flagcdn.com/w160/cz.png"
  },
  {
    "cca2": "DK",
    "official": "Kingdom of Denmark",
    "region": "Europe",
    "area": 43094,
    "drive": "Right",
    "languages": "Danish",
    "timezones": "UTC+01:00",
    "capital": "Copenhagen",
    "subregion": "Northern Europe",
    "population": 5903037,
    "name": "Denmark",
    "calling": "+45",
    "cca3": "DNK",
    "currency": "DKK (kr.) - Danish Krone",
    "flag": "https://flagcdn.com/w160/dk.png"
  },
  {
    "cca2": "DJ",
    "official": "Republic of Djibouti",
    "region": "Africa",
    "area": 23200,
    "drive": "Right",
    "languages": "Arabic, French",
    "timezones": "UTC+03:00",
    "capital": "Djibouti",
    "subregion": "Eastern Africa",
    "population": 1120849,
    "name": "Djibouti",
    "calling": "+253",
    "cca3": "DJI",
    "currency": "DJF (Fr) - Djiboutian Franc",
    "flag": "https://flagcdn.com/w160/dj.png"
  },
  {
    "cca2": "DM",
    "official": "Commonwealth of Dominica",
    "region": "Americas",
    "area": 751,
    "drive": "Left",
    "languages": "English",
    "timezones": "UTC-04:00",
    "capital": "Roseau",
    "subregion": "Caribbean",
    "population": 72737,
    "name": "Dominica",
    "calling": "+1-767",
    "cca3": "DMA",
    "currency": "XCD ($) - East Caribbean Dollar",
    "flag": "https://flagcdn.com/w160/dm.png"
  },
  {
    "cca2": "DO",
    "official": "Dominican Republic",
    "region": "Americas",
    "area": 48671,
    "drive": "Right",
    "languages": "Spanish",
    "timezones": "UTC-04:00",
    "capital": "Santo Domingo",
    "subregion": "Caribbean",
    "population": 11228821,
    "name": "Dominican Republic",
    "calling": "+1-809",
    "cca3": "DOM",
    "currency": "DOP ($) - Dominican Peso",
    "flag": "https://flagcdn.com/w160/do.png"
  },
  {
    "cca2": "EC",
    "official": "Republic of Ecuador",
    "region": "Americas",
    "area": 276841,
    "drive": "Right",
    "languages": "Spanish",
    "timezones": "UTC-06:00 to UTC-05:00",
    "capital": "Quito",
    "subregion": "South America",
    "population": 18001000,
    "name": "Ecuador",
    "calling": "+593",
    "cca3": "ECU",
    "currency": "USD ($) - United States Dollar",
    "flag": "https://flagcdn.com/w160/ec.png"
  },
  {
    "cca2": "EG",
    "official": "Arab Republic of Egypt",
    "region": "Africa",
    "area": 1002450,
    "drive": "Right",
    "languages": "Arabic",
    "timezones": "UTC+02:00",
    "capital": "Cairo",
    "subregion": "Northern Africa",
    "population": 109262178,
    "name": "Egypt",
    "calling": "+20",
    "cca3": "EGY",
    "currency": "EGP (E£) - Egyptian Pound",
    "flag": "https://flagcdn.com/w160/eg.png"
  },
  {
    "cca2": "SV",
    "official": "Republic of El Salvador",
    "region": "Americas",
    "area": 21041,
    "drive": "Right",
    "languages": "Spanish",
    "timezones": "UTC-06:00",
    "capital": "San Salvador",
    "subregion": "Central America",
    "population": 6336392,
    "name": "El Salvador",
    "calling": "+503",
    "cca3": "SLV",
    "currency": "USD ($) - United States Dollar",
    "flag": "https://flagcdn.com/w160/sv.png"
  },
  {
    "cca2": "GQ",
    "official": "Republic of Equatorial Guinea",
    "region": "Africa",
    "area": 28051,
    "drive": "Right",
    "languages": "Spanish, French, Portuguese",
    "timezones": "UTC+01:00",
    "capital": "Malabo",
    "subregion": "Middle Africa",
    "population": 1674908,
    "name": "Equatorial Guinea",
    "calling": "+240",
    "cca3": "GNQ",
    "currency": "XAF (Fr) - Central African CFA Franc",
    "flag": "https://flagcdn.com/w160/gq.png"
  },
  {
    "cca2": "ER",
    "official": "State of Eritrea",
    "region": "Africa",
    "area": 117600,
    "drive": "Right",
    "languages": "Tigrinya, Arabic, English",
    "timezones": "UTC+03:00",
    "capital": "Asmara",
    "subregion": "Eastern Africa",
    "population": 3684032,
    "name": "Eritrea",
    "calling": "+291",
    "cca3": "ERI",
    "currency": "ERN (Nkf) - Eritrean Nakfa",
    "flag": "https://flagcdn.com/w160/er.png"
  },
  {
    "cca2": "EE",
    "official": "Republic of Estonia",
    "region": "Europe",
    "area": 45227,
    "drive": "Right",
    "languages": "Estonian",
    "timezones": "UTC+02:00",
    "capital": "Tallinn",
    "subregion": "Northern Europe",
    "population": 1349248,
    "name": "Estonia",
    "calling": "+372",
    "cca3": "EST",
    "currency": "EUR (€) - Euro",
    "flag": "https://flagcdn.com/w160/ee.png"
  },
  {
    "cca2": "SZ",
    "official": "Kingdom of Eswatini",
    "region": "Africa",
    "area": 17364,
    "drive": "Left",
    "languages": "English, Swazi",
    "timezones": "UTC+02:00",
    "capital": "Mbabane",
    "subregion": "Southern Africa",
    "population": 1201670,
    "name": "Eswatini",
    "calling": "+268",
    "cca3": "SWZ",
    "currency": "SZL (L) - Swazi Lilangeni",
    "flag": "https://flagcdn.com/w160/sz.png"
  },
  {
    "cca2": "ET",
    "official": "Federal Democratic Republic of Ethiopia",
    "region": "Africa",
    "area": 1104300,
    "drive": "Right",
    "languages": "Amharic",
    "timezones": "UTC+03:00",
    "capital": "Addis Ababa",
    "subregion": "Eastern Africa",
    "population": 123379924,
    "name": "Ethiopia",
    "calling": "+251",
    "cca3": "ETH",
    "currency": "ETB (Br) - Ethiopian Birr",
    "flag": "https://flagcdn.com/w160/et.png"
  },
  {
    "cca2": "FJ",
    "official": "Republic of Fiji",
    "region": "Oceania",
    "area": 18272,
    "drive": "Left",
    "languages": "English, Fijian, Hindi",
    "timezones": "UTC+12:00",
    "capital": "Suva",
    "subregion": "Melanesia",
    "population": 929766,
    "name": "Fiji",
    "calling": "+679",
    "cca3": "FJI",
    "currency": "FJD ($) - Fijian Dollar",
    "flag": "https://flagcdn.com/w160/fj.png"
  },
  {
    "cca2": "FI",
    "official": "Republic of Finland",
    "region": "Europe",
    "area": 338424,
    "drive": "Right",
    "languages": "Finnish, Swedish",
    "timezones": "UTC+02:00",
    "capital": "Helsinki",
    "subregion": "Northern Europe",
    "population": 5556106,
    "name": "Finland",
    "calling": "+358",
    "cca3": "FIN",
    "currency": "EUR (€) - Euro",
    "flag": "https://flagcdn.com/w160/fi.png"
  },
  {
    "cca2": "FR",
    "official": "French Republic",
    "region": "Europe",
    "area": 551695,
    "drive": "Right",
    "languages": "French",
    "timezones": "UTC+01:00",
    "capital": "Paris",
    "subregion": "Western Europe",
    "population": 67971411,
    "name": "France",
    "calling": "+33",
    "cca3": "FRA",
    "currency": "EUR (€) - Euro",
    "flag": "https://flagcdn.com/w160/fr.png"
  },
  {
    "cca2": "GA",
    "official": "Gabonese Republic",
    "region": "Africa",
    "area": 267668,
    "drive": "Right",
    "languages": "French",
    "timezones": "UTC+01:00",
    "capital": "Libreville",
    "subregion": "Middle Africa",
    "population": 2388992,
    "name": "Gabon",
    "calling": "+241",
    "cca3": "GAB",
    "currency": "XAF (Fr) - Central African CFA Franc",
    "flag": "https://flagcdn.com/w160/ga.png"
  },
  {
    "cca2": "GM",
    "official": "Republic of the Gambia",
    "region": "Africa",
    "area": 10689,
    "drive": "Right",
    "languages": "English",
    "timezones": "UTC+00:00",
    "capital": "Banjul",
    "subregion": "Western Africa",
    "population": 2705992,
    "name": "Gambia",
    "calling": "+220",
    "cca3": "GMB",
    "currency": "GMD (D) - Gambian Dalasi",
    "flag": "https://flagcdn.com/w160/gm.png"
  },
  {
    "cca2": "GE",
    "official": "Georgia",
    "region": "Asia",
    "area": 69700,
    "drive": "Right",
    "languages": "Georgian",
    "timezones": "UTC+04:00",
    "capital": "Tbilisi",
    "subregion": "Western Asia",
    "population": 3712502,
    "name": "Georgia",
    "calling": "+995",
    "cca3": "GEO",
    "currency": "GEL (₾) - Georgian Lari",
    "flag": "https://flagcdn.com/w160/ge.png"
  },
  {
    "cca2": "DE",
    "official": "Federal Republic of Germany",
    "region": "Europe",
    "area": 357114,
    "drive": "Right",
    "languages": "German",
    "timezones": "UTC+01:00",
    "capital": "Berlin",
    "subregion": "Western Europe",
    "population": 84358845,
    "name": "Germany",
    "calling": "+49",
    "cca3": "DEU",
    "currency": "EUR (€) - Euro",
    "flag": "https://flagcdn.com/w160/de.png"
  },
  {
    "cca2": "GH",
    "official": "Republic of Ghana",
    "region": "Africa",
    "area": 238533,
    "drive": "Right",
    "languages": "English",
    "timezones": "UTC+00:00",
    "capital": "Accra",
    "subregion": "Western Africa",
    "population": 33475870,
    "name": "Ghana",
    "calling": "+233",
    "cca3": "GHA",
    "currency": "GHS (₵) - Ghanaian Cedi",
    "flag": "https://flagcdn.com/w160/gh.png"
  },
  {
    "cca2": "GR",
    "official": "Hellenic Republic",
    "region": "Europe",
    "area": 131957,
    "drive": "Right",
    "languages": "Greek",
    "timezones": "UTC+02:00",
    "capital": "Athens",
    "subregion": "Southern Europe",
    "population": 10432481,
    "name": "Greece",
    "calling": "+30",
    "cca3": "GRC",
    "currency": "EUR (€) - Euro",
    "flag": "https://flagcdn.com/w160/gr.png"
  },
  {
    "cca2": "GD",
    "official": "Grenada",
    "region": "Americas",
    "area": 344,
    "drive": "Left",
    "languages": "English",
    "timezones": "UTC-04:00",
    "capital": "St. George's",
    "subregion": "Caribbean",
    "population": 125438,
    "name": "Grenada",
    "calling": "+1-473",
    "cca3": "GRD",
    "currency": "XCD ($) - East Caribbean Dollar",
    "flag": "https://flagcdn.com/w160/gd.png"
  },
  {
    "cca2": "GT",
    "official": "Republic of Guatemala",
    "region": "Americas",
    "area": 108889,
    "drive": "Right",
    "languages": "Spanish",
    "timezones": "UTC-06:00",
    "capital": "Guatemala City",
    "subregion": "Central America",
    "population": 17843908,
    "name": "Guatemala",
    "calling": "+502",
    "cca3": "GTM",
    "currency": "GTQ (Q) - Guatemalan Quetzal",
    "flag": "https://flagcdn.com/w160/gt.png"
  },
  {
    "cca2": "GN",
    "official": "Republic of Guinea",
    "region": "Africa",
    "area": 245857,
    "drive": "Right",
    "languages": "French",
    "timezones": "UTC+00:00",
    "capital": "Conakry",
    "subregion": "Western Africa",
    "population": 13859341,
    "name": "Guinea",
    "calling": "+224",
    "cca3": "GIN",
    "currency": "GNF (Fr) - Guinean Franc",
    "flag": "https://flagcdn.com/w160/gn.png"
  },
  {
    "cca2": "GW",
    "official": "Republic of Guinea-Bissau",
    "region": "Africa",
    "area": 36125,
    "drive": "Right",
    "languages": "Portuguese",
    "timezones": "UTC+00:00",
    "capital": "Bissau",
    "subregion": "Western Africa",
    "population": 2105566,
    "name": "Guinea-Bissau",
    "calling": "+245",
    "cca3": "GNB",
    "currency": "XOF (Fr) - West African CFA Franc",
    "flag": "https://flagcdn.com/w160/gw.png"
  },
  {
    "cca2": "GY",
    "official": "Co-operative Republic of Guyana",
    "region": "Americas",
    "area": 214969,
    "drive": "Left",
    "languages": "English",
    "timezones": "UTC-04:00",
    "capital": "Georgetown",
    "subregion": "South America",
    "population": 808726,
    "name": "Guyana",
    "calling": "+592",
    "cca3": "GUY",
    "currency": "GYD ($) - Guyanese Dollar",
    "flag": "https://flagcdn.com/w160/gy.png"
  },
  {
    "cca2": "HT",
    "official": "Republic of Haiti",
    "region": "Americas",
    "area": 27750,
    "drive": "Right",
    "languages": "French, Haitian Creole",
    "timezones": "UTC-05:00",
    "capital": "Port-au-Prince",
    "subregion": "Caribbean",
    "population": 11584996,
    "name": "Haiti",
    "calling": "+509",
    "cca3": "HTI",
    "currency": "HTG (G) - Haitian Gourde",
    "flag": "https://flagcdn.com/w160/ht.png"
  },
  {
    "cca2": "HN",
    "official": "Republic of Honduras",
    "region": "Americas",
    "area": 112492,
    "drive": "Right",
    "languages": "Spanish",
    "timezones": "UTC-06:00",
    "capital": "Tegucigalpa",
    "subregion": "Central America",
    "population": 10432860,
    "name": "Honduras",
    "calling": "+504",
    "cca3": "HND",
    "currency": "HNL (L) - Honduran Lempira",
    "flag": "https://flagcdn.com/w160/hn.png"
  },
  {
    "cca2": "HU",
    "official": "Hungary",
    "region": "Europe",
    "area": 93028,
    "drive": "Right",
    "languages": "Hungarian",
    "timezones": "UTC+01:00",
    "capital": "Budapest",
    "subregion": "Eastern Europe",
    "population": 9686000,
    "name": "Hungary",
    "calling": "+36",
    "cca3": "HUN",
    "currency": "HUF (Ft) - Hungarian Forint",
    "flag": "https://flagcdn.com/w160/hu.png"
  },
  {
    "cca2": "IS",
    "official": "Iceland",
    "region": "Europe",
    "area": 103000,
    "drive": "Right",
    "languages": "Icelandic",
    "timezones": "UTC+00:00",
    "capital": "Reykjavik",
    "subregion": "Northern Europe",
    "population": 382003,
    "name": "Iceland",
    "calling": "+354",
    "cca3": "ISL",
    "currency": "ISK (kr) - Icelandic Króna",
    "flag": "https://flagcdn.com/w160/is.png"
  },
  {
    "cca2": "IN",
    "official": "Republic of India",
    "region": "Asia",
    "area": 3287263,
    "drive": "Left",
    "languages": "Hindi, English",
    "timezones": "UTC+05:30",
    "capital": "New Delhi",
    "subregion": "Southern Asia",
    "population": 1417173173,
    "name": "India",
    "calling": "+91",
    "cca3": "IND",
    "currency": "INR (₹) - Indian Rupee",
    "flag": "https://flagcdn.com/w160/in.png"
  },
  {
    "cca2": "ID",
    "official": "Republic of Indonesia",
    "region": "Asia",
    "area": 1904569,
    "drive": "Left",
    "languages": "Indonesian",
    "timezones": "UTC+07:00 to UTC+09:00",
    "capital": "Jakarta",
    "subregion": "South-Eastern Asia",
    "population": 275501339,
    "name": "Indonesia",
    "calling": "+62",
    "cca3": "IDN",
    "currency": "IDR (Rp) - Indonesian Rupiah",
    "flag": "https://flagcdn.com/w160/id.png"
  },
  {
    "cca2": "IR",
    "official": "Islamic Republic of Iran",
    "region": "Asia",
    "area": 1648195,
    "drive": "Right",
    "languages": "Persian (Farsi)",
    "timezones": "UTC+03:30",
    "capital": "Tehran",
    "subregion": "Southern Asia",
    "population": 88550570,
    "name": "Iran",
    "calling": "+98",
    "cca3": "IRN",
    "currency": "IRR (﷼) - Iranian Rial",
    "flag": "https://flagcdn.com/w160/ir.png"
  },
  {
    "cca2": "IQ",
    "official": "Republic of Iraq",
    "region": "Asia",
    "area": 438317,
    "drive": "Right",
    "languages": "Arabic, Kurdish",
    "timezones": "UTC+03:00",
    "capital": "Baghdad",
    "subregion": "Western Asia",
    "population": 44496122,
    "name": "Iraq",
    "calling": "+964",
    "cca3": "IRQ",
    "currency": "IQD (ع.د) - Iraqi Dinar",
    "flag": "https://flagcdn.com/w160/iq.png"
  },
  {
    "cca2": "IE",
    "official": "Republic of Ireland",
    "region": "Europe",
    "area": 70273,
    "drive": "Left",
    "languages": "Irish, English",
    "timezones": "UTC+00:00",
    "capital": "Dublin",
    "subregion": "Northern Europe",
    "population": 5127170,
    "name": "Ireland",
    "calling": "+353",
    "cca3": "IRL",
    "currency": "EUR (€) - Euro",
    "flag": "https://flagcdn.com/w160/ie.png"
  },
  {
    "cca2": "IL",
    "official": "State of Israel",
    "region": "Asia",
    "area": 20770,
    "drive": "Right",
    "languages": "Hebrew, Arabic",
    "timezones": "UTC+02:00",
    "capital": "Jerusalem",
    "subregion": "Western Asia",
    "population": 9550600,
    "name": "Israel",
    "calling": "+972",
    "cca3": "ISR",
    "currency": "ILS (₪) - Israeli New Shekel",
    "flag": "https://flagcdn.com/w160/il.png"
  },
  {
    "cca2": "IT",
    "official": "Italian Republic",
    "region": "Europe",
    "area": 301340,
    "drive": "Right",
    "languages": "Italian",
    "timezones": "UTC+01:00",
    "capital": "Rome",
    "subregion": "Southern Europe",
    "population": 58850717,
    "name": "Italy",
    "calling": "+39",
    "cca3": "ITA",
    "currency": "EUR (€) - Euro",
    "flag": "https://flagcdn.com/w160/it.png"
  },
  {
    "cca2": "CI",
    "official": "Republic of Côte d'Ivoire",
    "region": "Africa",
    "area": 322463,
    "drive": "Right",
    "languages": "French",
    "timezones": "UTC+00:00",
    "capital": "Yamoussoukro",
    "subregion": "Western Africa",
    "population": 29389150,
    "name": "Ivory Coast",
    "calling": "+225",
    "cca3": "CIV",
    "currency": "XOF (Fr) - West African CFA Franc",
    "flag": "https://flagcdn.com/w160/ci.png"
  },
  {
    "cca2": "JM",
    "official": "Jamaica",
    "region": "Americas",
    "area": 10991,
    "drive": "Left",
    "languages": "English",
    "timezones": "UTC-05:00",
    "capital": "Kingston",
    "subregion": "Caribbean",
    "population": 2827377,
    "name": "Jamaica",
    "calling": "+1-876",
    "cca3": "JAM",
    "currency": "JMD ($) - Jamaican Dollar",
    "flag": "https://flagcdn.com/w160/jm.png"
  },
  {
    "cca2": "JP",
    "official": "Japan",
    "region": "Asia",
    "area": 377930,
    "drive": "Left",
    "languages": "Japanese",
    "timezones": "UTC+09:00",
    "capital": "Tokyo",
    "subregion": "Eastern Asia",
    "population": 125124986,
    "name": "Japan",
    "calling": "+81",
    "cca3": "JPN",
    "currency": "JPY (¥) - Japanese Yen",
    "flag": "https://flagcdn.com/w160/jp.png"
  },
  {
    "cca2": "JO",
    "official": "Hashemite Kingdom of Jordan",
    "region": "Asia",
    "area": 89342,
    "drive": "Right",
    "languages": "Arabic",
    "timezones": "UTC+03:00",
    "capital": "Amman",
    "subregion": "Western Asia",
    "population": 11285869,
    "name": "Jordan",
    "calling": "+962",
    "cca3": "JOR",
    "currency": "JOD (د.ا) - Jordanian Dinar",
    "flag": "https://flagcdn.com/w160/jo.png"
  },
  {
    "cca2": "KZ",
    "official": "Republic of Kazakhstan",
    "region": "Asia",
    "area": 2724900,
    "drive": "Right",
    "languages": "Kazakh, Russian",
    "timezones": "UTC+05:00 to UTC+06:00",
    "capital": "Astana",
    "subregion": "Central Asia",
    "population": 19621972,
    "name": "Kazakhstan",
    "calling": "+7",
    "cca3": "KAZ",
    "currency": "KZT (₸) - Kazakhstani Tenge",
    "flag": "https://flagcdn.com/w160/kz.png"
  },
  {
    "cca2": "KE",
    "official": "Republic of Kenya",
    "region": "Africa",
    "area": 580367,
    "drive": "Left",
    "languages": "English, Swahili",
    "timezones": "UTC+03:00",
    "capital": "Nairobi",
    "subregion": "Eastern Africa",
    "population": 54027487,
    "name": "Kenya",
    "calling": "+254",
    "cca3": "KEN",
    "currency": "KES (Sh) - Kenyan Shilling",
    "flag": "https://flagcdn.com/w160/ke.png"
  },
  {
    "cca2": "KI",
    "official": "Independent and Sovereign Republic of Kiribati",
    "region": "Oceania",
    "area": 811,
    "drive": "Left",
    "languages": "English, Gilbertese",
    "timezones": "UTC+12:00 to UTC+14:00",
    "capital": "South Tarawa",
    "subregion": "Micronesia",
    "population": 131232,
    "name": "Kiribati",
    "calling": "+686",
    "cca3": "KIR",
    "currency": "AUD ($) - Australian Dollar",
    "flag": "https://flagcdn.com/w160/ki.png"
  },
  {
    "cca2": "KW",
    "official": "State of Kuwait",
    "region": "Asia",
    "area": 17818,
    "drive": "Right",
    "languages": "Arabic",
    "timezones": "UTC+03:00",
    "capital": "Kuwait City",
    "subregion": "Western Asia",
    "population": 4268873,
    "name": "Kuwait",
    "calling": "+965",
    "cca3": "KWT",
    "currency": "KWD (د.ك) - Kuwaiti Dinar",
    "flag": "https://flagcdn.com/w160/kw.png"
  },
  {
    "cca2": "KG",
    "official": "Kyrgyz Republic",
    "region": "Asia",
    "area": 199951,
    "drive": "Right",
    "languages": "Kyrgyz, Russian",
    "timezones": "UTC+06:00",
    "capital": "Bishkek",
    "subregion": "Central Asia",
    "population": 6964000,
    "name": "Kyrgyzstan",
    "calling": "+996",
    "cca3": "KGZ",
    "currency": "KGS (с) - Kyrgyzstani Som",
    "flag": "https://flagcdn.com/w160/kg.png"
  },
  {
    "cca2": "LA",
    "official": "Lao People's Democratic Republic",
    "region": "Asia",
    "area": 236800,
    "drive": "Right",
    "languages": "Lao",
    "timezones": "UTC+07:00",
    "capital": "Vientiane",
    "subregion": "South-Eastern Asia",
    "population": 7529475,
    "name": "Laos",
    "calling": "+856",
    "cca3": "LAO",
    "currency": "LAK (₭) - Lao Kip",
    "flag": "https://flagcdn.com/w160/la.png"
  },
  {
    "cca2": "LV",
    "official": "Republic of Latvia",
    "region": "Europe",
    "area": 64589,
    "drive": "Right",
    "languages": "Latvian",
    "timezones": "UTC+02:00",
    "capital": "Riga",
    "subregion": "Northern Europe",
    "population": 1875757,
    "name": "Latvia",
    "calling": "+371",
    "cca3": "LVA",
    "currency": "EUR (€) - Euro",
    "flag": "https://flagcdn.com/w160/lv.png"
  },
  {
    "cca2": "LB",
    "official": "Lebanese Republic",
    "region": "Asia",
    "area": 10452,
    "drive": "Right",
    "languages": "Arabic, French",
    "timezones": "UTC+02:00",
    "capital": "Beirut",
    "subregion": "Western Asia",
    "population": 5489739,
    "name": "Lebanon",
    "calling": "+961",
    "cca3": "LBN",
    "currency": "LBP (ل.ل) - Lebanese Pound",
    "flag": "https://flagcdn.com/w160/lb.png"
  },
  {
    "cca2": "LS",
    "official": "Kingdom of Lesotho",
    "region": "Africa",
    "area": 30355,
    "drive": "Left",
    "languages": "English, Sotho",
    "timezones": "UTC+02:00",
    "capital": "Maseru",
    "subregion": "Southern Africa",
    "population": 2305825,
    "name": "Lesotho",
    "calling": "+266",
    "cca3": "LSO",
    "currency": "LSL (L) - Lesotho Loti",
    "flag": "https://flagcdn.com/w160/ls.png"
  },
  {
    "cca2": "LR",
    "official": "Republic of Liberia",
    "region": "Africa",
    "area": 111369,
    "drive": "Right",
    "languages": "English",
    "timezones": "UTC+00:00",
    "capital": "Monrovia",
    "subregion": "Western Africa",
    "population": 5302681,
    "name": "Liberia",
    "calling": "+231",
    "cca3": "LBR",
    "currency": "LRD ($) - Liberian Dollar",
    "flag": "https://flagcdn.com/w160/lr.png"
  },
  {
    "cca2": "LY",
    "official": "State of Libya",
    "region": "Africa",
    "area": 1759540,
    "drive": "Right",
    "languages": "Arabic",
    "timezones": "UTC+02:00",
    "capital": "Tripoli",
    "subregion": "Northern Africa",
    "population": 6812341,
    "name": "Libya",
    "calling": "+218",
    "cca3": "LBY",
    "currency": "LYD (ل.د) - Libyan Dinar",
    "flag": "https://flagcdn.com/w160/ly.png"
  },
  {
    "cca2": "LI",
    "official": "Principality of Liechtenstein",
    "region": "Europe",
    "area": 160,
    "drive": "Right",
    "languages": "German",
    "timezones": "UTC+01:00",
    "capital": "Vaduz",
    "subregion": "Western Europe",
    "population": 39327,
    "name": "Liechtenstein",
    "calling": "+423",
    "cca3": "LIE",
    "currency": "CHF (CHF) - Swiss Franc",
    "flag": "https://flagcdn.com/w160/li.png"
  },
  {
    "cca2": "LT",
    "official": "Republic of Lithuania",
    "region": "Europe",
    "area": 65300,
    "drive": "Right",
    "languages": "Lithuanian",
    "timezones": "UTC+02:00",
    "capital": "Vilnius",
    "subregion": "Northern Europe",
    "population": 2833242,
    "name": "Lithuania",
    "calling": "+370",
    "cca3": "LTU",
    "currency": "EUR (€) - Euro",
    "flag": "https://flagcdn.com/w160/lt.png"
  },
  {
    "cca2": "LU",
    "official": "Grand Duchy of Luxembourg",
    "region": "Europe",
    "area": 2586,
    "drive": "Right",
    "languages": "Luxembourgish, French, German",
    "timezones": "UTC+01:00",
    "capital": "Luxembourg City",
    "subregion": "Western Europe",
    "population": 653103,
    "name": "Luxembourg",
    "calling": "+352",
    "cca3": "LUX",
    "currency": "EUR (€) - Euro",
    "flag": "https://flagcdn.com/w160/lu.png"
  },
  {
    "cca2": "MG",
    "official": "Republic of Madagascar",
    "region": "Africa",
    "area": 587041,
    "drive": "Right",
    "languages": "Malagasy, French",
    "timezones": "UTC+03:00",
    "capital": "Antananarivo",
    "subregion": "Eastern Africa",
    "population": 29611714,
    "name": "Madagascar",
    "calling": "+261",
    "cca3": "MDG",
    "currency": "MGA (Ar) - Malagasy Ariary",
    "flag": "https://flagcdn.com/w160/mg.png"
  },
  {
    "cca2": "MW",
    "official": "Republic of Malawi",
    "region": "Africa",
    "area": 118484,
    "drive": "Left",
    "languages": "English, Chewa",
    "timezones": "UTC+02:00",
    "capital": "Lilongwe",
    "subregion": "Eastern Africa",
    "population": 20405317,
    "name": "Malawi",
    "calling": "+265",
    "cca3": "MWI",
    "currency": "MWK (MK) - Malawian Kwacha",
    "flag": "https://flagcdn.com/w160/mw.png"
  },
  {
    "cca2": "MY",
    "official": "Malaysia",
    "region": "Asia",
    "area": 330803,
    "drive": "Left",
    "languages": "Malay",
    "timezones": "UTC+08:00",
    "capital": "Kuala Lumpur",
    "subregion": "South-Eastern Asia",
    "population": 33938221,
    "name": "Malaysia",
    "calling": "+60",
    "cca3": "MYS",
    "currency": "MYR (RM) - Malaysian Ringgit",
    "flag": "https://flagcdn.com/w160/my.png"
  },
  {
    "cca2": "MV",
    "official": "Republic of Maldives",
    "region": "Asia",
    "area": 300,
    "drive": "Left",
    "languages": "Dhivehi",
    "timezones": "UTC+05:00",
    "capital": "Malé",
    "subregion": "Southern Asia",
    "population": 523781,
    "name": "Maldives",
    "calling": "+960",
    "cca3": "MDV",
    "currency": "MVR (.ރ) - Maldivian Rufiyaa",
    "flag": "https://flagcdn.com/w160/mv.png"
  },
  {
    "cca2": "ML",
    "official": "Republic of Mali",
    "region": "Africa",
    "area": 1240192,
    "drive": "Right",
    "languages": "French, Bambara",
    "timezones": "UTC+00:00",
    "capital": "Bamako",
    "subregion": "Western Africa",
    "population": 22593590,
    "name": "Mali",
    "calling": "+223",
    "cca3": "MLI",
    "currency": "XOF (Fr) - West African CFA Franc",
    "flag": "https://flagcdn.com/w160/ml.png"
  },
  {
    "cca2": "MT",
    "official": "Republic of Malta",
    "region": "Europe",
    "area": 316,
    "drive": "Left",
    "languages": "Maltese, English",
    "timezones": "UTC+01:00",
    "capital": "Valletta",
    "subregion": "Southern Europe",
    "population": 533286,
    "name": "Malta",
    "calling": "+356",
    "cca3": "MLT",
    "currency": "EUR (€) - Euro",
    "flag": "https://flagcdn.com/w160/mt.png"
  },
  {
    "cca2": "MH",
    "official": "Republic of the Marshall Islands",
    "region": "Oceania",
    "area": 181,
    "drive": "Right",
    "languages": "Marshallese, English",
    "timezones": "UTC+12:00",
    "capital": "Majuro",
    "subregion": "Micronesia",
    "population": 41569,
    "name": "Marshall Islands",
    "calling": "+692",
    "cca3": "MHL",
    "currency": "USD ($) - United States Dollar",
    "flag": "https://flagcdn.com/w160/mh.png"
  },
  {
    "cca2": "MR",
    "official": "Islamic Republic of Mauritania",
    "region": "Africa",
    "area": 1030700,
    "drive": "Right",
    "languages": "Arabic",
    "timezones": "UTC+00:00",
    "capital": "Nouakchott",
    "subregion": "Western Africa",
    "population": 4736139,
    "name": "Mauritania",
    "calling": "+222",
    "cca3": "MRT",
    "currency": "MRU (UM) - Mauritanian Ouguiya",
    "flag": "https://flagcdn.com/w160/mr.png"
  },
  {
    "cca2": "MU",
    "official": "Republic of Mauritius",
    "region": "Africa",
    "area": 2040,
    "drive": "Left",
    "languages": "English, French, Mauritian Creole",
    "timezones": "UTC+04:00",
    "capital": "Port Louis",
    "subregion": "Eastern Africa",
    "population": 1262523,
    "name": "Mauritius",
    "calling": "+230",
    "cca3": "MUS",
    "currency": "MUR (₨) - Mauritian Rupee",
    "flag": "https://flagcdn.com/w160/mu.png"
  },
  {
    "cca2": "MX",
    "official": "United Mexican States",
    "region": "Americas",
    "area": 1964375,
    "drive": "Right",
    "languages": "Spanish",
    "timezones": "UTC-08:00 to UTC-05:00",
    "capital": "Mexico City",
    "subregion": "North America",
    "population": 127504125,
    "name": "Mexico",
    "calling": "+52",
    "cca3": "MEX",
    "currency": "MXN ($) - Mexican Peso",
    "flag": "https://flagcdn.com/w160/mx.png"
  },
  {
    "cca2": "FM",
    "official": "Federated States of Micronesia",
    "region": "Oceania",
    "area": 702,
    "drive": "Right",
    "languages": "English",
    "timezones": "UTC+10:00 to UTC+11:00",
    "capital": "Palikir",
    "subregion": "Micronesia",
    "population": 114164,
    "name": "Micronesia",
    "calling": "+691",
    "cca3": "FSM",
    "currency": "USD ($) - United States Dollar",
    "flag": "https://flagcdn.com/w160/fm.png"
  },
  {
    "cca2": "MD",
    "official": "Republic of Moldova",
    "region": "Europe",
    "area": 33846,
    "drive": "Right",
    "languages": "Romanian",
    "timezones": "UTC+02:00",
    "capital": "Chișinău",
    "subregion": "Eastern Europe",
    "population": 2538894,
    "name": "Moldova",
    "calling": "+373",
    "cca3": "MDA",
    "currency": "MDL (L) - Moldovan Leu",
    "flag": "https://flagcdn.com/w160/md.png"
  },
  {
    "cca2": "MC",
    "official": "Principality of Monaco",
    "region": "Europe",
    "area": 2,
    "drive": "Right",
    "languages": "French",
    "timezones": "UTC+01:00",
    "capital": "Monaco",
    "subregion": "Western Europe",
    "population": 39050,
    "name": "Monaco",
    "calling": "+377",
    "cca3": "MCO",
    "currency": "EUR (€) - Euro",
    "flag": "https://flagcdn.com/w160/mc.png"
  },
  {
    "cca2": "MN",
    "official": "Mongolia",
    "region": "Asia",
    "area": 1564116,
    "drive": "Right",
    "languages": "Mongolian",
    "timezones": "UTC+07:00 to UTC+08:00",
    "capital": "Ulaanbaatar",
    "subregion": "Eastern Asia",
    "population": 3398366,
    "name": "Mongolia",
    "calling": "+976",
    "cca3": "MNG",
    "currency": "MNT (₮) - Mongolian Tögrög",
    "flag": "https://flagcdn.com/w160/mn.png"
  },
  {
    "cca2": "ME",
    "official": "Montenegro",
    "region": "Europe",
    "area": 13812,
    "drive": "Right",
    "languages": "Montenegrin",
    "timezones": "UTC+01:00",
    "capital": "Podgorica",
    "subregion": "Southern Europe",
    "population": 617213,
    "name": "Montenegro",
    "calling": "+382",
    "cca3": "MNE",
    "currency": "EUR (€) - Euro",
    "flag": "https://flagcdn.com/w160/me.png"
  },
  {
    "cca2": "MA",
    "official": "Kingdom of Morocco",
    "region": "Africa",
    "area": 446550,
    "drive": "Right",
    "languages": "Arabic, Berber",
    "timezones": "UTC+01:00",
    "capital": "Rabat",
    "subregion": "Northern Africa",
    "population": 37457971,
    "name": "Morocco",
    "calling": "+212",
    "cca3": "MAR",
    "currency": "MAD (د.م.) - Moroccan Dirham",
    "flag": "https://flagcdn.com/w160/ma.png"
  },
  {
    "cca2": "MZ",
    "official": "Republic of Mozambique",
    "region": "Africa",
    "area": 801590,
    "drive": "Left",
    "languages": "Portuguese",
    "timezones": "UTC+02:00",
    "capital": "Maputo",
    "subregion": "Eastern Africa",
    "population": 32969518,
    "name": "Mozambique",
    "calling": "+258",
    "cca3": "MOZ",
    "currency": "MZN (MT) - Mozambican Metical",
    "flag": "https://flagcdn.com/w160/mz.png"
  },
  {
    "cca2": "MM",
    "official": "Republic of the Union of Myanmar",
    "region": "Asia",
    "area": 676578,
    "drive": "Right",
    "languages": "Burmese",
    "timezones": "UTC+06:30",
    "capital": "Naypyidaw",
    "subregion": "South-Eastern Asia",
    "population": 54179306,
    "name": "Myanmar",
    "calling": "+95",
    "cca3": "MMR",
    "currency": "MMK (Ks) - Burmese Kyat",
    "flag": "https://flagcdn.com/w160/mm.png"
  },
  {
    "cca2": "NA",
    "official": "Republic of Namibia",
    "region": "Africa",
    "area": 825615,
    "drive": "Left",
    "languages": "English",
    "timezones": "UTC+02:00",
    "capital": "Windhoek",
    "subregion": "Southern Africa",
    "population": 2567012,
    "name": "Namibia",
    "calling": "+264",
    "cca3": "NAM",
    "currency": "NAD ($) - Namibian Dollar",
    "flag": "https://flagcdn.com/w160/na.png"
  },
  {
    "cca2": "NR",
    "official": "Republic of Nauru",
    "region": "Oceania",
    "area": 21,
    "drive": "Left",
    "languages": "Nauruan, English",
    "timezones": "UTC+12:00",
    "capital": "Yaren",
    "subregion": "Micronesia",
    "population": 12668,
    "name": "Nauru",
    "calling": "+674",
    "cca3": "NRU",
    "currency": "AUD ($) - Australian Dollar",
    "flag": "https://flagcdn.com/w160/nr.png"
  },
  {
    "cca2": "NP",
    "official": "Federal Democratic Republic of Nepal",
    "region": "Asia",
    "area": 147181,
    "drive": "Left",
    "languages": "Nepali",
    "timezones": "UTC+05:45",
    "capital": "Kathmandu",
    "subregion": "Southern Asia",
    "population": 30547580,
    "name": "Nepal",
    "calling": "+977",
    "cca3": "NPL",
    "currency": "NPR (₨) - Nepalese Rupee",
    "flag": "https://flagcdn.com/w160/np.png"
  },
  {
    "cca2": "NL",
    "official": "Kingdom of the Netherlands",
    "region": "Europe",
    "area": 41850,
    "drive": "Right",
    "languages": "Dutch",
    "timezones": "UTC+01:00",
    "capital": "Amsterdam",
    "subregion": "Western Europe",
    "population": 17700000,
    "name": "Netherlands",
    "calling": "+31",
    "cca3": "NLD",
    "currency": "EUR (€) - Euro",
    "flag": "https://flagcdn.com/w160/nl.png"
  },
  {
    "cca2": "NZ",
    "official": "New Zealand",
    "region": "Oceania",
    "area": 270467,
    "drive": "Left",
    "languages": "English, Māori",
    "timezones": "UTC+12:00 to UTC+12:45",
    "capital": "Wellington",
    "subregion": "Australia and New Zealand",
    "population": 5124100,
    "name": "New Zealand",
    "calling": "+64",
    "cca3": "NZL",
    "currency": "NZD ($) - New Zealand Dollar",
    "flag": "https://flagcdn.com/w160/nz.png"
  },
  {
    "cca2": "NI",
    "official": "Republic of Nicaragua",
    "region": "Americas",
    "area": 130373,
    "drive": "Right",
    "languages": "Spanish",
    "timezones": "UTC-06:00",
    "capital": "Managua",
    "subregion": "Central America",
    "population": 6948392,
    "name": "Nicaragua",
    "calling": "+505",
    "cca3": "NIC",
    "currency": "NIO (C$) - Nicaraguan Córdoba",
    "flag": "https://flagcdn.com/w160/ni.png"
  },
  {
    "cca2": "NE",
    "official": "Republic of Niger",
    "region": "Africa",
    "area": 1267000,
    "drive": "Right",
    "languages": "French, Hausa",
    "timezones": "UTC+01:00",
    "capital": "Niamey",
    "subregion": "Western Africa",
    "population": 26207977,
    "name": "Niger",
    "calling": "+227",
    "cca3": "NER",
    "currency": "XOF (Fr) - West African CFA Franc",
    "flag": "https://flagcdn.com/w160/ne.png"
  },
  {
    "cca2": "NG",
    "official": "Federal Republic of Nigeria",
    "region": "Africa",
    "area": 923768,
    "drive": "Right",
    "languages": "English, Hausa, Yoruba, Igbo",
    "timezones": "UTC+01:00",
    "capital": "Abuja",
    "subregion": "Western Africa",
    "population": 218541212,
    "name": "Nigeria",
    "calling": "+234",
    "cca3": "NGA",
    "currency": "NGN (₦) - Nigerian Naira",
    "flag": "https://flagcdn.com/w160/ng.png"
  },
  {
    "cca2": "KP",
    "official": "Democratic People's Republic of Korea",
    "region": "Asia",
    "area": 120538,
    "drive": "Right",
    "languages": "Korean",
    "timezones": "UTC+09:00",
    "capital": "Pyongyang",
    "subregion": "Eastern Asia",
    "population": 26069416,
    "name": "North Korea",
    "calling": "+850",
    "cca3": "PRK",
    "currency": "KPW (₩) - North Korean Won",
    "flag": "https://flagcdn.com/w160/kp.png"
  },
  {
    "cca2": "MK",
    "official": "Republic of North Macedonia",
    "region": "Europe",
    "area": 25713,
    "drive": "Right",
    "languages": "Macedonian, Albanian",
    "timezones": "UTC+01:00",
    "capital": "Skopje",
    "subregion": "Southern Europe",
    "population": 1836713,
    "name": "North Macedonia",
    "calling": "+389",
    "cca3": "MKD",
    "currency": "MKD (ден) - Macedonian Denar",
    "flag": "https://flagcdn.com/w160/mk.png"
  },
  {
    "cca2": "NO",
    "official": "Kingdom of Norway",
    "region": "Europe",
    "area": 323802,
    "drive": "Right",
    "languages": "Norwegian",
    "timezones": "UTC+01:00",
    "capital": "Oslo",
    "subregion": "Northern Europe",
    "population": 5434319,
    "name": "Norway",
    "calling": "+47",
    "cca3": "NOR",
    "currency": "NOK (kr) - Norwegian Krone",
    "flag": "https://flagcdn.com/w160/no.png"
  },
  {
    "cca2": "OM",
    "official": "Sultanate of Oman",
    "region": "Asia",
    "area": 309500,
    "drive": "Right",
    "languages": "Arabic",
    "timezones": "UTC+04:00",
    "capital": "Muscat",
    "subregion": "Western Asia",
    "population": 4576298,
    "name": "Oman",
    "calling": "+968",
    "cca3": "OMN",
    "currency": "OMR (ر.ع.) - Omani Rial",
    "flag": "https://flagcdn.com/w160/om.png"
  },
  {
    "cca2": "PK",
    "official": "Islamic Republic of Pakistan",
    "region": "Asia",
    "area": 881912,
    "drive": "Left",
    "languages": "Urdu, English",
    "timezones": "UTC+05:00",
    "capital": "Islamabad",
    "subregion": "Southern Asia",
    "population": 241499431,
    "name": "Pakistan",
    "calling": "+92",
    "cca3": "PAK",
    "currency": "PKR (₨) - Pakistani Rupee",
    "flag": "https://flagcdn.com/w160/pk.png"
  },
  {
    "cca2": "PW",
    "official": "Republic of Palau",
    "region": "Oceania",
    "area": 459,
    "drive": "Right",
    "languages": "Palauan, English",
    "timezones": "UTC+09:00",
    "capital": "Ngerulmud",
    "subregion": "Micronesia",
    "population": 18055,
    "name": "Palau",
    "calling": "+680",
    "cca3": "PLW",
    "currency": "USD ($) - United States Dollar",
    "flag": "https://flagcdn.com/w160/pw.png"
  },
  {
    "cca2": "PS",
    "official": "State of Palestine",
    "region": "Asia",
    "area": 6020,
    "drive": "Right",
    "languages": "Arabic",
    "timezones": "UTC+02:00",
    "capital": "Ramallah",
    "subregion": "Western Asia",
    "population": 5250072,
    "name": "Palestine",
    "calling": "+970",
    "cca3": "PSE",
    "currency": "ILS (₪) - Israeli Shekel, JOD - Dinar",
    "flag": "https://flagcdn.com/w160/ps.png"
  },
  {
    "cca2": "PA",
    "official": "Republic of Panama",
    "region": "Americas",
    "area": 75417,
    "drive": "Right",
    "languages": "Spanish",
    "timezones": "UTC-05:00",
    "capital": "Panama City",
    "subregion": "Central America",
    "population": 4408581,
    "name": "Panama",
    "calling": "+507",
    "cca3": "PAN",
    "currency": "PAB (B/.) - Panamanian Balboa, USD",
    "flag": "https://flagcdn.com/w160/pa.png"
  },
  {
    "cca2": "PG",
    "official": "Independent State of Papua New Guinea",
    "region": "Oceania",
    "area": 462840,
    "drive": "Left",
    "languages": "English, Tok Pisin, Hiri Motu",
    "timezones": "UTC+10:00 to UTC+11:00",
    "capital": "Port Moresby",
    "subregion": "Melanesia",
    "population": 10142615,
    "name": "Papua New Guinea",
    "calling": "+675",
    "cca3": "PNG",
    "currency": "PGK (K) - Papua New Guinean Kina",
    "flag": "https://flagcdn.com/w160/pg.png"
  },
  {
    "cca2": "PY",
    "official": "Republic of Paraguay",
    "region": "Americas",
    "area": 406752,
    "drive": "Right",
    "languages": "Spanish, Guaraní",
    "timezones": "UTC-04:00",
    "capital": "Asunción",
    "subregion": "South America",
    "population": 6780744,
    "name": "Paraguay",
    "calling": "+595",
    "cca3": "PRY",
    "currency": "PYG (₲) - Paraguayan Guaraní",
    "flag": "https://flagcdn.com/w160/py.png"
  },
  {
    "cca2": "PE",
    "official": "Republic of Peru",
    "region": "Americas",
    "area": 1285216,
    "drive": "Right",
    "languages": "Spanish, Quechua, Aymara",
    "timezones": "UTC-05:00",
    "capital": "Lima",
    "subregion": "South America",
    "population": 34049588,
    "name": "Peru",
    "calling": "+51",
    "cca3": "PER",
    "currency": "PEN (S/.) - Peruvian Sol",
    "flag": "https://flagcdn.com/w160/pe.png"
  },
  {
    "cca2": "PH",
    "official": "Republic of the Philippines",
    "region": "Asia",
    "area": 300000,
    "drive": "Right",
    "languages": "Filipino, English",
    "timezones": "UTC+08:00",
    "capital": "Manila",
    "subregion": "South-Eastern Asia",
    "population": 115559009,
    "name": "Philippines",
    "calling": "+63",
    "cca3": "PHL",
    "currency": "PHP (₱) - Philippine Peso",
    "flag": "https://flagcdn.com/w160/ph.png"
  },
  {
    "cca2": "PL",
    "official": "Republic of Poland",
    "region": "Europe",
    "area": 312696,
    "drive": "Right",
    "languages": "Polish",
    "timezones": "UTC+01:00",
    "capital": "Warsaw",
    "subregion": "Eastern Europe",
    "population": 37698000,
    "name": "Poland",
    "calling": "+48",
    "cca3": "POL",
    "currency": "PLN (zł) - Polish Złoty",
    "flag": "https://flagcdn.com/w160/pl.png"
  },
  {
    "cca2": "PT",
    "official": "Portuguese Republic",
    "region": "Europe",
    "area": 92090,
    "drive": "Right",
    "languages": "Portuguese",
    "timezones": "UTC+00:00",
    "capital": "Lisbon",
    "subregion": "Southern Europe",
    "population": 10467366,
    "name": "Portugal",
    "calling": "+351",
    "cca3": "PRT",
    "currency": "EUR (€) - Euro",
    "flag": "https://flagcdn.com/w160/pt.png"
  },
  {
    "cca2": "QA",
    "official": "State of Qatar",
    "region": "Asia",
    "area": 11586,
    "drive": "Right",
    "languages": "Arabic",
    "timezones": "UTC+03:00",
    "capital": "Doha",
    "subregion": "Western Asia",
    "population": 2695122,
    "name": "Qatar",
    "calling": "+974",
    "cca3": "QAT",
    "currency": "QAR (ر.ق) - Qatari Riyal",
    "flag": "https://flagcdn.com/w160/qa.png"
  },
  {
    "cca2": "RO",
    "official": "Romania",
    "region": "Europe",
    "area": 238391,
    "drive": "Right",
    "languages": "Romanian",
    "timezones": "UTC+02:00",
    "capital": "Bucharest",
    "subregion": "Eastern Europe",
    "population": 19051562,
    "name": "Romania",
    "calling": "+40",
    "cca3": "ROU",
    "currency": "RON (lei) - Romanian Leu",
    "flag": "https://flagcdn.com/w160/ro.png"
  },
  {
    "cca2": "RU",
    "official": "Russian Federation",
    "region": "Europe/Asia",
    "area": 17098242,
    "drive": "Right",
    "languages": "Russian",
    "timezones": "UTC+02:00 to UTC+12:00",
    "capital": "Moscow",
    "subregion": "Eastern Europe",
    "population": 144236933,
    "name": "Russia",
    "calling": "+7",
    "cca3": "RUS",
    "currency": "RUB (₽) - Russian Ruble",
    "flag": "https://flagcdn.com/w160/ru.png"
  },
  {
    "cca2": "RW",
    "official": "Republic of Rwanda",
    "region": "Africa",
    "area": 26338,
    "drive": "Right",
    "languages": "Kinyarwanda, French, English",
    "timezones": "UTC+02:00",
    "capital": "Kigali",
    "subregion": "Eastern Africa",
    "population": 13776698,
    "name": "Rwanda",
    "calling": "+250",
    "cca3": "RWA",
    "currency": "RWF (Fr) - Rwandan Franc",
    "flag": "https://flagcdn.com/w160/rw.png"
  },
  {
    "cca2": "KN",
    "official": "Federation of Saint Christopher and Nevis",
    "region": "Americas",
    "area": 261,
    "drive": "Left",
    "languages": "English",
    "timezones": "UTC-04:00",
    "capital": "Basseterre",
    "subregion": "Caribbean",
    "population": 47658,
    "name": "Saint Kitts and Nevis",
    "calling": "+1-869",
    "cca3": "KNA",
    "currency": "XCD ($) - East Caribbean Dollar",
    "flag": "https://flagcdn.com/w160/kn.png"
  },
  {
    "cca2": "LC",
    "official": "Saint Lucia",
    "region": "Americas",
    "area": 616,
    "drive": "Left",
    "languages": "English",
    "timezones": "UTC-04:00",
    "capital": "Castries",
    "subregion": "Caribbean",
    "population": 179857,
    "name": "Saint Lucia",
    "calling": "+1-758",
    "cca3": "LCA",
    "currency": "XCD ($) - East Caribbean Dollar",
    "flag": "https://flagcdn.com/w160/lc.png"
  },
  {
    "cca2": "VC",
    "official": "Saint Vincent and the Grenadines",
    "region": "Americas",
    "area": 389,
    "drive": "Left",
    "languages": "English",
    "timezones": "UTC-04:00",
    "capital": "Kingstown",
    "subregion": "Caribbean",
    "population": 103948,
    "name": "Saint Vincent and the Grenadines",
    "calling": "+1-784",
    "cca3": "VCT",
    "currency": "XCD ($) - East Caribbean Dollar",
    "flag": "https://flagcdn.com/w160/vc.png"
  },
  {
    "cca2": "WS",
    "official": "Independent State of Samoa",
    "region": "Oceania",
    "area": 2842,
    "drive": "Left",
    "languages": "Samoan, English",
    "timezones": "UTC+13:00",
    "capital": "Apia",
    "subregion": "Polynesia",
    "population": 222382,
    "name": "Samoa",
    "calling": "+685",
    "cca3": "WSM",
    "currency": "WST (T) - Samoan Tālā",
    "flag": "https://flagcdn.com/w160/ws.png"
  },
  {
    "cca2": "SM",
    "official": "Republic of San Marino",
    "region": "Europe",
    "area": 61,
    "drive": "Right",
    "languages": "Italian",
    "timezones": "UTC+01:00",
    "capital": "City of San Marino",
    "subregion": "Southern Europe",
    "population": 33660,
    "name": "San Marino",
    "calling": "+378",
    "cca3": "SMR",
    "currency": "EUR (€) - Euro",
    "flag": "https://flagcdn.com/w160/sm.png"
  },
  {
    "cca2": "ST",
    "official": "Democratic Republic of São Tomé and Príncipe",
    "region": "Africa",
    "area": 964,
    "drive": "Right",
    "languages": "Portuguese",
    "timezones": "UTC+00:00",
    "capital": "São Tomé",
    "subregion": "Middle Africa",
    "population": 227380,
    "name": "Sao Tome and Principe",
    "calling": "+239",
    "cca3": "STP",
    "currency": "STN (Db) - São Tomé and Príncipe Dobra",
    "flag": "https://flagcdn.com/w160/st.png"
  },
  {
    "cca2": "SA",
    "official": "Kingdom of Saudi Arabia",
    "region": "Asia",
    "area": 2149690,
    "drive": "Right",
    "languages": "Arabic",
    "timezones": "UTC+03:00",
    "capital": "Riyadh",
    "subregion": "Western Asia",
    "population": 36408820,
    "name": "Saudi Arabia",
    "calling": "+966",
    "cca3": "SAU",
    "currency": "SAR (ر.س) - Saudi Riyal",
    "flag": "https://flagcdn.com/w160/sa.png"
  },
  {
    "cca2": "SN",
    "official": "Republic of Senegal",
    "region": "Africa",
    "area": 196722,
    "drive": "Right",
    "languages": "French, Wolof",
    "timezones": "UTC+00:00",
    "capital": "Dakar",
    "subregion": "Western Africa",
    "population": 17316449,
    "name": "Senegal",
    "calling": "+221",
    "cca3": "SEN",
    "currency": "XOF (Fr) - West African CFA Franc",
    "flag": "https://flagcdn.com/w160/sn.png"
  },
  {
    "cca2": "RS",
    "official": "Republic of Serbia",
    "region": "Europe",
    "area": 88361,
    "drive": "Right",
    "languages": "Serbian",
    "timezones": "UTC+01:00",
    "capital": "Belgrade",
    "subregion": "Southern Europe",
    "population": 6664449,
    "name": "Serbia",
    "calling": "+381",
    "cca3": "SRB",
    "currency": "RSD (дин.) - Serbian Dinar",
    "flag": "https://flagcdn.com/w160/rs.png"
  },
  {
    "cca2": "SC",
    "official": "Republic of Seychelles",
    "region": "Africa",
    "area": 452,
    "drive": "Left",
    "languages": "Seychellois Creole, English, French",
    "timezones": "UTC+04:00",
    "capital": "Victoria",
    "subregion": "Eastern Africa",
    "population": 107118,
    "name": "Seychelles",
    "calling": "+248",
    "cca3": "SYC",
    "currency": "SCR (₨) - Seychellois Rupee",
    "flag": "https://flagcdn.com/w160/sc.png"
  },
  {
    "cca2": "SL",
    "official": "Republic of Sierra Leone",
    "region": "Africa",
    "area": 71740,
    "drive": "Right",
    "languages": "English",
    "timezones": "UTC+00:00",
    "capital": "Freetown",
    "subregion": "Western Africa",
    "population": 8605718,
    "name": "Sierra Leone",
    "calling": "+232",
    "cca3": "SLE",
    "currency": "SLE (Le) - Sierra Leonean Leone",
    "flag": "https://flagcdn.com/w160/sl.png"
  },
  {
    "cca2": "SG",
    "official": "Republic of Singapore",
    "region": "Asia",
    "area": 728,
    "drive": "Left",
    "languages": "English, Malay, Mandarin, Tamil",
    "timezones": "UTC+08:00",
    "capital": "Singapore",
    "subregion": "South-Eastern Asia",
    "population": 5637000,
    "name": "Singapore",
    "calling": "+65",
    "cca3": "SGP",
    "currency": "SGD ($) - Singapore Dollar",
    "flag": "https://flagcdn.com/w160/sg.png"
  },
  {
    "cca2": "SK",
    "official": "Slovak Republic",
    "region": "Europe",
    "area": 49037,
    "drive": "Right",
    "languages": "Slovak",
    "timezones": "UTC+01:00",
    "capital": "Bratislava",
    "subregion": "Central Europe",
    "population": 5428792,
    "name": "Slovakia",
    "calling": "+421",
    "cca3": "SVK",
    "currency": "EUR (€) - Euro",
    "flag": "https://flagcdn.com/w160/sk.png"
  },
  {
    "cca2": "SI",
    "official": "Republic of Slovenia",
    "region": "Europe",
    "area": 20273,
    "drive": "Right",
    "languages": "Slovene",
    "timezones": "UTC+01:00",
    "capital": "Ljubljana",
    "subregion": "Southern Europe",
    "population": 2116972,
    "name": "Slovenia",
    "calling": "+386",
    "cca3": "SVN",
    "currency": "EUR (€) - Euro",
    "flag": "https://flagcdn.com/w160/si.png"
  },
  {
    "cca2": "SB",
    "official": "Solomon Islands",
    "region": "Oceania",
    "area": 28896,
    "drive": "Left",
    "languages": "English, Pijin",
    "timezones": "UTC+11:00",
    "capital": "Honiara",
    "subregion": "Melanesia",
    "population": 724273,
    "name": "Solomon Islands",
    "calling": "+677",
    "cca3": "SLB",
    "currency": "SBD ($) - Solomon Islands Dollar",
    "flag": "https://flagcdn.com/w160/sb.png"
  },
  {
    "cca2": "SO",
    "official": "Federal Republic of Somalia",
    "region": "Africa",
    "area": 637657,
    "drive": "Right",
    "languages": "Somali, Arabic",
    "timezones": "UTC+03:00",
    "capital": "Mogadishu",
    "subregion": "Eastern Africa",
    "population": 17597511,
    "name": "Somalia",
    "calling": "+252",
    "cca3": "SOM",
    "currency": "SOS (Sh) - Somali Shilling",
    "flag": "https://flagcdn.com/w160/so.png"
  },
  {
    "cca2": "ZA",
    "official": "Republic of South Africa",
    "region": "Africa",
    "area": 1221037,
    "drive": "Left",
    "languages": "Zulu, Xhosa, Afrikaans, English",
    "timezones": "UTC+02:00",
    "capital": "Pretoria",
    "subregion": "Southern Africa",
    "population": 59893885,
    "name": "South Africa",
    "calling": "+27",
    "cca3": "ZAF",
    "currency": "ZAR (R) - South African Rand",
    "flag": "https://flagcdn.com/w160/za.png"
  },
  {
    "cca2": "KR",
    "official": "Republic of Korea",
    "region": "Asia",
    "area": 100210,
    "drive": "Right",
    "languages": "Korean",
    "timezones": "UTC+09:00",
    "capital": "Seoul",
    "subregion": "Eastern Asia",
    "population": 51628117,
    "name": "South Korea",
    "calling": "+82",
    "cca3": "KOR",
    "currency": "KRW (₩) - South Korean Won",
    "flag": "https://flagcdn.com/w160/kr.png"
  },
  {
    "cca2": "SS",
    "official": "Republic of South Sudan",
    "region": "Africa",
    "area": 619745,
    "drive": "Right",
    "languages": "English",
    "timezones": "UTC+02:00",
    "capital": "Juba",
    "subregion": "Eastern Africa",
    "population": 10913164,
    "name": "South Sudan",
    "calling": "+211",
    "cca3": "SSD",
    "currency": "SSP (£) - South Sudanese Pound",
    "flag": "https://flagcdn.com/w160/ss.png"
  },
  {
    "cca2": "ES",
    "official": "Kingdom of Spain",
    "region": "Europe",
    "area": 505992,
    "drive": "Right",
    "languages": "Spanish, Catalan, Galician, Basque",
    "timezones": "UTC+01:00",
    "capital": "Madrid",
    "subregion": "Southern Europe",
    "population": 47778340,
    "name": "Spain",
    "calling": "+34",
    "cca3": "ESP",
    "currency": "EUR (€) - Euro",
    "flag": "https://flagcdn.com/w160/es.png"
  },
  {
    "cca2": "LK",
    "official": "Democratic Socialist Republic of Sri Lanka",
    "region": "Asia",
    "area": 65610,
    "drive": "Left",
    "languages": "Sinhala, Tamil",
    "timezones": "UTC+05:30",
    "capital": "Colombo",
    "subregion": "Southern Asia",
    "population": 22181000,
    "name": "Sri Lanka",
    "calling": "+94",
    "cca3": "LKA",
    "currency": "LKR (Rs) - Sri Lankan Rupee",
    "flag": "https://flagcdn.com/w160/lk.png"
  },
  {
    "cca2": "SD",
    "official": "Republic of the Sudan",
    "region": "Africa",
    "area": 1861484,
    "drive": "Right",
    "languages": "Arabic, English",
    "timezones": "UTC+02:00",
    "capital": "Khartoum",
    "subregion": "Northern Africa",
    "population": 46874204,
    "name": "Sudan",
    "calling": "+249",
    "cca3": "SDN",
    "currency": "SDG (ج.س.) - Sudanese Pound",
    "flag": "https://flagcdn.com/w160/sd.png"
  },
  {
    "cca2": "SR",
    "official": "Republic of Suriname",
    "region": "Americas",
    "area": 163820,
    "drive": "Left",
    "languages": "Dutch",
    "timezones": "UTC-03:00",
    "capital": "Paramaribo",
    "subregion": "South America",
    "population": 618040,
    "name": "Suriname",
    "calling": "+597",
    "cca3": "SUR",
    "currency": "SRD ($) - Surinamese Dollar",
    "flag": "https://flagcdn.com/w160/sr.png"
  },
  {
    "cca2": "SE",
    "official": "Kingdom of Sweden",
    "region": "Europe",
    "area": 450295,
    "drive": "Right",
    "languages": "Swedish",
    "timezones": "UTC+01:00",
    "capital": "Stockholm",
    "subregion": "Northern Europe",
    "population": 10521556,
    "name": "Sweden",
    "calling": "+46",
    "cca3": "SWE",
    "currency": "SEK (kr) - Swedish Krona",
    "flag": "https://flagcdn.com/w160/se.png"
  },
  {
    "cca2": "CH",
    "official": "Swiss Confederation",
    "region": "Europe",
    "area": 41285,
    "drive": "Right",
    "languages": "German, French, Italian, Romansh",
    "timezones": "UTC+01:00",
    "capital": "Bern",
    "subregion": "Western Europe",
    "population": 8775760,
    "name": "Switzerland",
    "calling": "+41",
    "cca3": "CHE",
    "currency": "CHF (CHF) - Swiss Franc",
    "flag": "https://flagcdn.com/w160/ch.png"
  },
  {
    "cca2": "SY",
    "official": "Syrian Arab Republic",
    "region": "Asia",
    "area": 185180,
    "drive": "Right",
    "languages": "Arabic",
    "timezones": "UTC+03:00",
    "capital": "Damascus",
    "subregion": "Western Asia",
    "population": 22125249,
    "name": "Syria",
    "calling": "+963",
    "cca3": "SYR",
    "currency": "SYP (£S) - Syrian Pound",
    "flag": "https://flagcdn.com/w160/sy.png"
  },
  {
    "cca2": "TW",
    "official": "Republic of China (Taiwan)",
    "region": "Asia",
    "area": 36193,
    "drive": "Right",
    "languages": "Mandarin Chinese",
    "timezones": "UTC+08:00",
    "capital": "Taipei",
    "subregion": "Eastern Asia",
    "population": 23894000,
    "name": "Taiwan",
    "calling": "+886",
    "cca3": "TWN",
    "currency": "TWD ($) - New Taiwan Dollar",
    "flag": "https://flagcdn.com/w160/tw.png"
  },
  {
    "cca2": "TJ",
    "official": "Republic of Tajikistan",
    "region": "Asia",
    "area": 143100,
    "drive": "Right",
    "languages": "Tajik",
    "timezones": "UTC+05:00",
    "capital": "Dushanbe",
    "subregion": "Central Asia",
    "population": 9952787,
    "name": "Tajikistan",
    "calling": "+992",
    "cca3": "TJK",
    "currency": "TJS (ЅМ) - Tajikistani Somoni",
    "flag": "https://flagcdn.com/w160/tj.png"
  },
  {
    "cca2": "TZ",
    "official": "United Republic of Tanzania",
    "region": "Africa",
    "area": 947303,
    "drive": "Left",
    "languages": "Swahili, English",
    "timezones": "UTC+03:00",
    "capital": "Dodoma",
    "subregion": "Eastern Africa",
    "population": 65497748,
    "name": "Tanzania",
    "calling": "+255",
    "cca3": "TZA",
    "currency": "TZS (Sh) - Tanzanian Shilling",
    "flag": "https://flagcdn.com/w160/tz.png"
  },
  {
    "cca2": "TH",
    "official": "Kingdom of Thailand",
    "region": "Asia",
    "area": 513120,
    "drive": "Left",
    "languages": "Thai",
    "timezones": "UTC+07:00",
    "capital": "Bangkok",
    "subregion": "South-Eastern Asia",
    "population": 71697030,
    "name": "Thailand",
    "calling": "+66",
    "cca3": "THA",
    "currency": "THB (฿) - Thai Baht",
    "flag": "https://flagcdn.com/w160/th.png"
  },
  {
    "cca2": "TL",
    "official": "Democratic Republic of Timor-Leste",
    "region": "Asia",
    "area": 14874,
    "drive": "Left",
    "languages": "Tetum, Portuguese",
    "timezones": "UTC+09:00",
    "capital": "Dili",
    "subregion": "South-Eastern Asia",
    "population": 1341296,
    "name": "Timor-Leste",
    "calling": "+670",
    "cca3": "TLS",
    "currency": "USD ($) - United States Dollar",
    "flag": "https://flagcdn.com/w160/tl.png"
  },
  {
    "cca2": "TG",
    "official": "Togolese Republic",
    "region": "Africa",
    "area": 56785,
    "drive": "Right",
    "languages": "French",
    "timezones": "UTC+00:00",
    "capital": "Lomé",
    "subregion": "Western Africa",
    "population": 8848699,
    "name": "Togo",
    "calling": "+228",
    "cca3": "TGO",
    "currency": "XOF (Fr) - West African CFA Franc",
    "flag": "https://flagcdn.com/w160/tg.png"
  },
  {
    "cca2": "TO",
    "official": "Kingdom of Tonga",
    "region": "Oceania",
    "area": 747,
    "drive": "Left",
    "languages": "Tongan, English",
    "timezones": "UTC+13:00",
    "capital": "Nuku'alofa",
    "subregion": "Polynesia",
    "population": 106858,
    "name": "Tonga",
    "calling": "+676",
    "cca3": "TON",
    "currency": "TOP (T$) - Tongan Paʻanga",
    "flag": "https://flagcdn.com/w160/to.png"
  },
  {
    "cca2": "TT",
    "official": "Republic of Trinidad and Tobago",
    "region": "Americas",
    "area": 5130,
    "drive": "Left",
    "languages": "English",
    "timezones": "UTC-04:00",
    "capital": "Port of Spain",
    "subregion": "Caribbean",
    "population": 1531044,
    "name": "Trinidad and Tobago",
    "calling": "+1-868",
    "cca3": "TTO",
    "currency": "TTD ($) - Trinidad and Tobago Dollar",
    "flag": "https://flagcdn.com/w160/tt.png"
  },
  {
    "cca2": "TN",
    "official": "Republic of Tunisia",
    "region": "Africa",
    "area": 163610,
    "drive": "Right",
    "languages": "Arabic",
    "timezones": "UTC+01:00",
    "capital": "Tunis",
    "subregion": "Northern Africa",
    "population": 12356117,
    "name": "Tunisia",
    "calling": "+216",
    "cca3": "TUN",
    "currency": "TND (د.ت) - Tunisian Dinar",
    "flag": "https://flagcdn.com/w160/tn.png"
  },
  {
    "cca2": "TR",
    "official": "Republic of Türkiye",
    "region": "Asia/Europe",
    "area": 783562,
    "drive": "Right",
    "languages": "Turkish",
    "timezones": "UTC+03:00",
    "capital": "Ankara",
    "subregion": "Western Asia",
    "population": 85341241,
    "name": "Turkey",
    "calling": "+90",
    "cca3": "TUR",
    "currency": "TRY (₺) - Turkish Lira",
    "flag": "https://flagcdn.com/w160/tr.png"
  },
  {
    "cca2": "TM",
    "official": "Turkmenistan",
    "region": "Asia",
    "area": 488100,
    "drive": "Right",
    "languages": "Turkmen",
    "timezones": "UTC+05:00",
    "capital": "Ashgabat",
    "subregion": "Central Asia",
    "population": 6430770,
    "name": "Turkmenistan",
    "calling": "+993",
    "cca3": "TKM",
    "currency": "TMT (m) - Turkmenistani Manat",
    "flag": "https://flagcdn.com/w160/tm.png"
  },
  {
    "cca2": "TV",
    "official": "Tuvalu",
    "region": "Oceania",
    "area": 26,
    "drive": "Left",
    "languages": "Tuvaluan, English",
    "timezones": "UTC+12:00",
    "capital": "Funafuti",
    "subregion": "Polynesia",
    "population": 11312,
    "name": "Tuvalu",
    "calling": "+688",
    "cca3": "TUV",
    "currency": "AUD ($) - Australian Dollar",
    "flag": "https://flagcdn.com/w160/tv.png"
  },
  {
    "cca2": "UG",
    "official": "Republic of Uganda",
    "region": "Africa",
    "area": 241550,
    "drive": "Left",
    "languages": "English, Swahili",
    "timezones": "UTC+03:00",
    "capital": "Kampala",
    "subregion": "Eastern Africa",
    "population": 47249585,
    "name": "Uganda",
    "calling": "+256",
    "cca3": "UGA",
    "currency": "UGX (Sh) - Ugandan Shilling",
    "flag": "https://flagcdn.com/w160/ug.png"
  },
  {
    "cca2": "UA",
    "official": "Ukraine",
    "region": "Europe",
    "area": 603500,
    "drive": "Right",
    "languages": "Ukrainian",
    "timezones": "UTC+02:00",
    "capital": "Kyiv",
    "subregion": "Eastern Europe",
    "population": 38000000,
    "name": "Ukraine",
    "calling": "+380",
    "cca3": "UKR",
    "currency": "UAH (₴) - Ukrainian Hryvnia",
    "flag": "https://flagcdn.com/w160/ua.png"
  },
  {
    "cca2": "AE",
    "official": "United Arab Emirates",
    "region": "Asia",
    "area": 83600,
    "drive": "Right",
    "languages": "Arabic",
    "timezones": "UTC+04:00",
    "capital": "Abu Dhabi",
    "subregion": "Western Asia",
    "population": 9441129,
    "name": "United Arab Emirates",
    "calling": "+971",
    "cca3": "ARE",
    "currency": "AED (د.إ) - UAE Dirham",
    "flag": "https://flagcdn.com/w160/ae.png"
  },
  {
    "cca2": "GB",
    "official": "United Kingdom of Great Britain and Northern Ireland",
    "region": "Europe",
    "area": 242900,
    "drive": "Left",
    "languages": "English",
    "timezones": "UTC+00:00",
    "capital": "London",
    "subregion": "Northern Europe",
    "population": 67736802,
    "name": "United Kingdom",
    "calling": "+44",
    "cca3": "GBR",
    "currency": "GBP (£) - British Pound",
    "flag": "https://flagcdn.com/w160/gb.png"
  },
  {
    "cca2": "US",
    "official": "United States of America",
    "region": "Americas",
    "area": 9372610,
    "drive": "Right",
    "languages": "English",
    "timezones": "UTC-12:00 to UTC+12:00",
    "capital": "Washington, D.C.",
    "subregion": "Northern America",
    "population": 333287557,
    "name": "United States",
    "calling": "+1",
    "cca3": "USA",
    "currency": "USD ($) - United States Dollar",
    "flag": "https://flagcdn.com/w160/us.png"
  },
  {
    "cca2": "UY",
    "official": "Oriental Republic of Uruguay",
    "region": "Americas",
    "area": 176215,
    "drive": "Right",
    "languages": "Spanish",
    "timezones": "UTC-03:00",
    "capital": "Montevideo",
    "subregion": "South America",
    "population": 3422794,
    "name": "Uruguay",
    "calling": "+598",
    "cca3": "URY",
    "currency": "UYU ($) - Uruguayan Peso",
    "flag": "https://flagcdn.com/w160/uy.png"
  },
  {
    "cca2": "UZ",
    "official": "Republic of Uzbekistan",
    "region": "Asia",
    "area": 447400,
    "drive": "Right",
    "languages": "Uzbek",
    "timezones": "UTC+05:00",
    "capital": "Tashkent",
    "subregion": "Central Asia",
    "population": 36024946,
    "name": "Uzbekistan",
    "calling": "+998",
    "cca3": "UZB",
    "currency": "UZS (so'm) - Uzbekistani So'm",
    "flag": "https://flagcdn.com/w160/uz.png"
  },
  {
    "cca2": "VU",
    "official": "Republic of Vanuatu",
    "region": "Oceania",
    "area": 12189,
    "drive": "Right",
    "languages": "Bislama, English, French",
    "timezones": "UTC+11:00",
    "capital": "Port Vila",
    "subregion": "Melanesia",
    "population": 326740,
    "name": "Vanuatu",
    "calling": "+678",
    "cca3": "VUT",
    "currency": "VUV (Vt) - Vanuatu Vatu",
    "flag": "https://flagcdn.com/w160/vu.png"
  },
  {
    "cca2": "VA",
    "official": "Vatican City State",
    "region": "Europe",
    "area": 1,
    "drive": "Right",
    "languages": "Italian, Latin",
    "timezones": "UTC+01:00",
    "capital": "Vatican City",
    "subregion": "Southern Europe",
    "population": 825,
    "name": "Vatican City",
    "calling": "+379",
    "cca3": "VAT",
    "currency": "EUR (€) - Euro",
    "flag": "https://flagcdn.com/w160/va.png"
  },
  {
    "cca2": "VE",
    "official": "Bolivarian Republic of Venezuela",
    "region": "Americas",
    "area": 916445,
    "drive": "Right",
    "languages": "Spanish",
    "timezones": "UTC-04:00",
    "capital": "Caracas",
    "subregion": "South America",
    "population": 28301696,
    "name": "Venezuela",
    "calling": "+58",
    "cca3": "VEN",
    "currency": "VES (Bs.S) - Venezuelan Bolívar",
    "flag": "https://flagcdn.com/w160/ve.png"
  },
  {
    "cca2": "VN",
    "official": "Socialist Republic of Vietnam",
    "region": "Asia",
    "area": 331212,
    "drive": "Right",
    "languages": "Vietnamese",
    "timezones": "UTC+07:00",
    "capital": "Hanoi",
    "subregion": "South-Eastern Asia",
    "population": 98186856,
    "name": "Vietnam",
    "calling": "+84",
    "cca3": "VNM",
    "currency": "VND (₫) - Vietnamese Đồng",
    "flag": "https://flagcdn.com/w160/vn.png"
  },
  {
    "cca2": "YE",
    "official": "Republic of Yemen",
    "region": "Asia",
    "area": 527968,
    "drive": "Right",
    "languages": "Arabic",
    "timezones": "UTC+03:00",
    "capital": "Sana'a",
    "subregion": "Western Asia",
    "population": 33696614,
    "name": "Yemen",
    "calling": "+967",
    "cca3": "YEM",
    "currency": "YER (﷼) - Yemeni Rial",
    "flag": "https://flagcdn.com/w160/ye.png"
  },
  {
    "cca2": "ZM",
    "official": "Republic of Zambia",
    "region": "Africa",
    "area": 752618,
    "drive": "Left",
    "languages": "English",
    "timezones": "UTC+02:00",
    "capital": "Lusaka",
    "subregion": "Eastern Africa",
    "population": 20017675,
    "name": "Zambia",
    "calling": "+260",
    "cca3": "ZMB",
    "currency": "ZMW (ZK) - Zambian Kwacha",
    "flag": "https://flagcdn.com/w160/zm.png"
  },
  {
    "cca2": "ZW",
    "official": "Republic of Zimbabwe",
    "region": "Africa",
    "area": 390757,
    "drive": "Left",
    "languages": "English, Shona, Ndebele",
    "timezones": "UTC+02:00",
    "capital": "Harare",
    "subregion": "Eastern Africa",
    "population": 16320537,
    "name": "Zimbabwe",
    "calling": "+263",
    "cca3": "ZWA",
    "currency": "ZWG (ZiG) - Zimbabwe Gold",
    "flag": "https://flagcdn.com/w160/zw.png"
  }
];